### ISSUE TITLE
Unable to publish plugin

### ISSUE THREAD

**Issue by bostjan** [roundcube/plugins.roundcube.net#4]
Error message:
No valid/supported repository was found at the given URL

At this uri:
https://github.com/teonsystems/roundcube-plugin-smart-autocomplete.git

What is the cause of this?

Tnx,
b.

**Comment by thomascube** [comment]
The issue should now be resolved after adding an authentication key for polling Github repositories. Can you please re-try and confirm?

**Comment by bostjan** [comment]
Nope, still the same error message.

Please feel free to test with this plugin, it is still in early alpha phase ATM:
https://github.com/teonsystems/roundcube-plugin-smart-autocomplete

b.

**Comment by bostjan** [comment]
There may very well be something wrong with the repo, and it would help tremendously if error message gave a clue about what is wrong.

**Comment by bostjan** [comment]
Just retried it, and there was one occurence where it got past initial submission and displayed "teon/smart_autocomplete" package name and asked for confirmation, but when I clicked "Confirm", the same error appears.

Network connectivity problems maybe?

b.

**Comment by bostjan** [comment]
Ok now it went through. Did you do something, or is your app hitting GitHub API rate limits or something? :)

b.

**Comment by bostjan** [comment]
Another problem:

When I click "Force Update" button this appears:

[RuntimeException] Failed to clone git@github.com:teonsystems/roundcube-plugin-smart-autocomplete.git, could not read packages from it Permission denied (publickey). fatal: The remote end hung up unexpectedly
Failed to clone the git@github.com:teonsystems/roundcube-plugin-smart-autocomplete.git repository, try running in interactive mode so that you can enter your GitHub credentials

b.

**Comment by thomascube** [comment]
Try using the `https://` url for your repository

**Comment by alecpl** [comment]
I guess we can close this.
