### ISSUE TITLE
Plugin not updating due to leading v in tag?

### ISSUE THREAD

**Issue by pimlie** [roundcube/plugins.roundcube.net#5]
Yesterday I released a new version for the [authres_status](https://github.com/pimlie/authres_status/releases) plugin. According to the packagist [about](https://packagist.org/about) you can tag new releases with or without a v in front. 
But for some reason the new version 'v0.4.0' was not picked up by plugins.roundcube.net, only when I added the tag '0.4.0' (without leading v) the new version was immediately recognised. 

Is this expected behaviour?

**Comment by thomascube** [comment]
I see the 0.4.0 version listed on https://plugins.roundcube.net/packages/roundcube/authres_status
Sometimes Packagist needs a moment to sync with Github. I assume this is resolved.

**Comment by pimlie** [comment]
@thomascube I already said the new version was recognised after removing the leading `v`, so the fact that it is listed on plugins.roundcube.net has nothing to do with this issue resolved or not ;)

> Sometimes Packagist needs a moment to sync with Github

In this case packagist immediately saw there was a new commit which was visible for the dev-master branch, it just wouldnt pick-up the new version tag. Anyway, maybe it was a temporary glitch. Will report back if it happens again.
