### ISSUE TITLE
plugins.roundcube.net package-json contains old version of plugin

### ISSUE THREAD

**Issue by Yannik** [roundcube/plugins.roundcube.net#7]
I'm trying to install the `texxasrulez/caldav_calendar` plugin like this: `composer require texxasrulez/caldav_calendar:dev-master`.

The [plugin page](https://plugins.roundcube.net/packages/texxasrulez/caldav_calendar#dev-master) shows `9d3795962c16580b3ae55febc76604c4e69daf01` as latest commit hash, which matches the one on github. 

However, installing the plugin like shown above, leads to an old version `08a38534b6cfcbef56392c96e67b3851e9b120a7` being installed. I've ofcourse tried clearing the composer cache, but this didn't help.

I've run composer with `-vvv` to find out why:

1. First, composer downloads https://plugins.roundcube.net/packages.json, which lists a number of provider$<hash>.json files. 
2. Then composer downloads https://plugins.roundcube.net/p/provider-latest%24ab791916ba19b1d772da67e29f167010888dbaed3d910ca3477b0134009f8dac.json, which was listed in `packages.json`. This lists `35a86d6cac917e9e1043cba0b1b9ba026d6bd0ee88b2fdf5835223fb7c2cca51` as packages.json-hash.
3. Therefore, composer next downloads https://plugins.roundcube.net/p/texxasrulez/caldav_calendar%2435a86d6cac917e9e1043cba0b1b9ba026d6bd0ee88b2fdf5835223fb7c2cca51.json. This file specifies the old `08a38534b6cfcbef56392c96e67b3851e9b120a7` git commit hash as the one of `dev-master`.

**Comment by thomascube** [comment]
This is a known problem and therefore we'll abandon our own plugins repository and move Roundcube plugins to packagist.org. Please read [our announcement](https://roundcube.net/news/2020/04/11/changes-in-roundcubes-plugin-repository).

**Comment by Yannik** [comment]
@thomascube Ok, is it safe to remove plugins.roundcube.net from composer.json and use packagist.org instead today? Or only after May 17th?

**Comment by thomascube** [comment]
@Yannik you can remove it if all of your required plugins have already migrated to packagist.org.
